test:
	@pandoc --self-contained --lua-filter=diagram_generator.lua --metadata=activate_python_path:"python3 --version" --metadata=python_path:"python3" --metadata=title:"README" README.md -o output.html

